# Check the documentation at https://goreleaser.com for more options
builds:
  - id: notation-local-signer
    dir: .
    main: ./cmd/notation-local-signer
    binary: notation-local-signer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
archives:
  - name_template: "{{.Binary}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
checksum:
  name_template: "{{ .Binary }}_{{ .Version }}_checksums.txt"
release:
  prerelease: auto
  draft: true