# Copyright The Notary Project Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: e2e-test

on:
  push:
  pull_request:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push to local registry
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .github/testdata
          push: true
          tags: localhost:5000/e2e:latest
      - name: Retrieve digest
        run: |
          echo "target_artifact_reference=localhost:5000/e2e@${{ steps.push.outputs.digest }}" >> "$GITHUB_ENV"
      
      # Setting up Notation CLI on the runner
      - name: Setup Notation
        uses: notaryproject/notation-action/setup@main
      
      # Sign artifact using notation plugin
      - name: Sign artifact
        uses: notaryproject/notation-action/sign@main
        env:
          E2E_SIGNING_KEY: ${{ secrets.E2E_SIGNING_KEY }}
        with:
          plugin_name: local-signer
          plugin_url: https://github.com/Two-Hearts/notation-action/releases/download/v0.1.0/notation-local-signer_0.1.0_linux_amd64.tar.gz
          plugin_checksum: 0732f03c9ec9529959a4915ffbf0d5483247dcb4b1687a540a6733f4f3968548
          key_id: .github/testdata/truststore/x509/ca/e2e/notation.crt
          target_artifact_reference: ${{ env.target_artifact_reference }}
          signature_format: cose
          plugin_config: |-
            env=E2E_SIGNING_KEY
      
      # Verify artifact
      - name: Verify artifact
        uses: notaryproject/notation-action/verify@main
        with:
          target_artifact_reference: ${{ env.target_artifact_reference }}
          trust_policy: .github/testdata/trustpolicy/trustpolicy.json
          trust_store: .github/testdata/truststore
 