name: Update major and minor versions
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  release:
    types: [published]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Tag new target
        run: | 
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=${VERSION%%.*}  
          git tag -f ${MAJOR} ${VERSION}
          git push origin ${MAJOR} --force